# Generated by Django 6.0.6 on 2026-06-13 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('TODO', 'Not done'), ('PROGRESS', 'In progress'), ('DONE', 'Complete')], default='TODO', max_length=8)),
                ('priority', models.CharField(choices=[('TODO', 'Not done'), ('PROGRESS', 'In progress'), ('DONE', 'Complete')], default='MEDIUM', max_length=8)),
                ('due_day', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
